==== START logs for container keda-operator-metrics-apiserver of pod kube-system/keda-operator-metrics-apiserver-6b7c5864b9-f7n22 ====
I0724 16:13:55.275342       1 welcome.go:34] "msg"="Starting metrics server" "logger"="keda_metrics_adapter"
I0724 16:13:55.275485       1 welcome.go:35] "msg"="KEDA Version: main" "logger"="keda_metrics_adapter"
I0724 16:13:55.275505       1 welcome.go:36] "msg"="Git Commit: " "logger"="keda_metrics_adapter"
I0724 16:13:55.275650       1 welcome.go:37] "msg"="Go Version: go1.24.1 X:systemcrypto" "logger"="keda_metrics_adapter"
I0724 16:13:55.275661       1 welcome.go:38] "msg"="Go OS/Arch: linux/amd64" "logger"="keda_metrics_adapter"
I0724 16:13:55.275721       1 welcome.go:39] "msg"="Running on Kubernetes 1.32" "logger"="keda_metrics_adapter" "version"={"major":"1","minor":"32","gitVersion":"v1.32.5","gitCommit":"9894294ef13a5b32803e3ca2c0d620a088cc84d1","gitTreeState":"clean","buildDate":"2025-05-21T16:17:25Z","goVersion":"go1.23.8","compiler":"gc","platform":"linux/amd64"}
I0724 16:13:55.275734       1 welcome.go:43] "msg"="WARNING: KEDA main hasn't been tested on Kubernetes v1.32.5" "logger"="keda_metrics_adapter"
I0724 16:13:55.275810       1 welcome.go:44] "msg"="You can check recommended versions on https://keda.sh" "logger"="keda_metrics_adapter"
I0724 16:13:55.276095       1 maxprocs.go:31] "msg"="maxprocs: Updating GOMAXPROCS=1: determined from CPU quota" "logger"="keda_metrics_adapter"
I0724 16:13:55.276581       1 main.go:111] "msg"="Connecting Metrics Service gRPC client to the server" "address"="keda-operator.kube-system.svc.cluster.local:9666" "logger"="keda_metrics_adapter"
I0724 16:13:55.297382       1 provider.go:56] "msg"="starting" "logger"="keda_metrics_adapter.provider"
I0724 16:13:55.297437       1 main.go:272] "msg"="starting adapter..." "logger"="keda_metrics_adapter"
I0724 16:13:55.297523       1 client.go:103] "msg"="Waiting for establishing a gRPC connection to KEDA Metrics Server" "logger"="keda_metrics_adapter.provider"
I0724 16:13:55.315867       1 main.go:184] "msg"="starting /metrics server endpoint" "logger"="keda_metrics_adapter"
W0724 16:13:55.337689       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
I0724 16:13:55.513629       1 secure_serving.go:213] Serving securely on [::]:6443
I0724 16:13:55.513689       1 requestheader_controller.go:172] Starting RequestHeaderAuthRequestController
I0724 16:13:55.513710       1 shared_informer.go:313] Waiting for caches to sync for RequestHeaderAuthRequestController
I0724 16:13:55.513742       1 dynamic_serving_content.go:135] "Starting controller" name="serving-cert::/certs/tls.crt::/certs/tls.key"
I0724 16:13:55.513843       1 tlsconfig.go:243] "Starting DynamicServingCertificateController"
I0724 16:13:55.513913       1 dynamic_cafile_content.go:160] "Starting controller" name="client-ca-bundle::/certs/ca.crt"
I0724 16:13:55.513988       1 configmap_cafile_content.go:205] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0724 16:13:55.513996       1 shared_informer.go:313] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0724 16:13:55.614007       1 shared_informer.go:320] Caches are synced for RequestHeaderAuthRequestController
I0724 16:13:55.614033       1 shared_informer.go:320] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
W0724 16:13:56.338385       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
W0724 16:13:57.636746       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
W0724 16:14:00.419898       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
W0724 16:14:03.905861       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
W0724 16:14:09.891082       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.165.174:9666", ServerName: "keda-operator.kube-system.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.165.174:9666: connect: connection refused"
I0724 16:14:22.334264       1 provider.go:64] "msg"="Connection to KEDA Metrics Service gRPC server has been successfully established" "logger"="keda_metrics_adapter.provider" "server"="keda-operator.kube-system.svc.cluster.local:9666"
E0724 16:19:07.818127       1 writers.go:122] "Unhandled Error" err="apiserver was unable to write a JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.818368       1 writers.go:122] "Unhandled Error" err="apiserver was unable to write a JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.818575       1 writers.go:122] "Unhandled Error" err="apiserver was unable to write a JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.818647       1 writers.go:122] "Unhandled Error" err="apiserver was unable to write a JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.819349       1 status.go:71] "Unhandled Error" err="apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"http: Handler timeout\"}: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.819416       1 status.go:71] "Unhandled Error" err="apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"http: Handler timeout\"}: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.819624       1 status.go:71] "Unhandled Error" err="apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"http: Handler timeout\"}: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.819669       1 status.go:71] "Unhandled Error" err="apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"http: Handler timeout\"}: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.820515       1 writers.go:135] "Unhandled Error" err="apiserver was unable to write a fallback JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.820735       1 writers.go:135] "Unhandled Error" err="apiserver was unable to write a fallback JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.821557       1 timeout.go:140] "Post-timeout activity" logger="UnhandledError" timeElapsed="4.107371ms" method="GET" path="/apis/external.metrics.k8s.io/v1beta1" result=null
E0724 16:19:07.821762       1 timeout.go:140] "Post-timeout activity" logger="UnhandledError" timeElapsed="4.927006ms" method="GET" path="/apis/external.metrics.k8s.io/v1beta1" result=null
E0724 16:19:07.821794       1 writers.go:135] "Unhandled Error" err="apiserver was unable to write a fallback JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.821858       1 writers.go:135] "Unhandled Error" err="apiserver was unable to write a fallback JSON response: http: Handler timeout" logger="UnhandledError"
E0724 16:19:07.822861       1 timeout.go:140] "Post-timeout activity" logger="UnhandledError" timeElapsed="5.489189ms" method="GET" path="/apis/external.metrics.k8s.io/v1beta1" result=null
E0724 16:19:07.822886       1 timeout.go:140] "Post-timeout activity" logger="UnhandledError" timeElapsed="5.000547ms" method="GET" path="/apis/external.metrics.k8s.io/v1beta1" result=null
E0724 16:19:27.250905       1 timeout.go:140] "Post-timeout activity" logger="UnhandledError" timeElapsed="1.201917ms" method="GET" path="/apis" result=null
==== END logs for container keda-operator-metrics-apiserver of pod kube-system/keda-operator-metrics-apiserver-6b7c5864b9-f7n22 ====
